echo "Initializing kittens..."
echo "Kittens initialized!"
echo "Retrieving kittens..."
echo "Kittens retrieved!"
echo "Stand by for kittens!"
echo "![Here's a kitten!](http://placekitten.com/g/200/300)"
echo "![More coming](http://placekitten.com/g/150/350)"
echo "![One more after this](http://placekitten.com/g/350/300)"
echo "![Big one](http://placekitten.com/g/500/500)"
echo "Hope you enjoyed those kittens!"
