echo "Initializing kittens..."
echo "Kittens initialized!"
echo "Retrieving kittens..."
echo "Kittens retrieved!"
echo "Stand by for kittens!"
echo "[Here's a kitten!](https://placekitten.com/g/200/300)"
echo "[Here's another kitten!](https://placekitten.com/g/300/200)"
echo "[Check out this kitten](https://placekitten.com/g/300/300)"
echo "[More coming](https://placekitten.com/g/150/350)"
echo "[One more after this](https://placekitten.com/g/350/300)"
echo "[Biggest one for last](https://placekitten.com/g/400/400)"
echo "Hope you enjoyed those kittens!"
